server:
  port: 9001

spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: http://user:123456@localhost:8761/eureka

feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true