server:
  port: 9001

spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true

feign-server:
  version: 0.7
