server:
  port: 9001

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: spring
    password: 123456

feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign-server:
  version: 0.7
