server:
  port: 8761
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # 从 ipAddress 改为了 ip-address
    appname: eureka-server
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.cloud.client.ip-address}:${server.port}/eureka/
  server:
    eviction-interval-timer-in-ms: 5000
    enable-self-preservation: false
spring:
  application:
    name: eureka-server
  security:
    user:
      name: user
      password: 123456
info:
  app:
    name: Eureka Server
