server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1016990109/spring-cloud-example.git
          search-paths: config-repo
        overrides:
          eureka.instance.prefer-ip-address: true
    bus:
      enabled: true
      trace:
        enabled: true
  security:
    user:
      name: config
      password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: spring
    password: 123456


eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"