server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/1016990109/spring-cloud-example.git
          search-paths: config-repo
        overrides:
          eureka.instance.prefer-ip-address: true
          eureka.instance.instance-id

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:123456@localhost:8761/eureka/